     var db = require("./models");

     db.User.create({
      username:"andrewwilliams",
      password:"abc11abc22",
      email:"andrewjameswilliams.aw@gmail.com"
    });
     db.User.create({
      username:"testUser1",
      password:"abc11abc22",
      email:"testuser1@gmail.com"
    });
     db.User.create({
      username:"testUser2",
      password:"abc11abc22",
      email:"testuser2@gmail.com"
    });
     db.User.create({
      username:"testUser3",
      password:"abc11abc22",
      email:"testuser3@gmail.com"
    });
     db.User.create({
      username:"testUser4",
      password:"abc11abc22",
      email:"testuser4@gmail.com"
    });
     db.Channel.create({
      channelDescription:"",
      name:"",
      UserId:"",
      category:""
    });
     db.Channel.create({
      channelDescription:"",
      name:"",
      UserId:"",
      category:""
    });
     db.Channel.create({
      channelDescription:"",
      name:"",
      UserId:"",
      category:""
    });
     db.Channel.create({
      channelDescription:"",
      name:"",
      UserId:"",
      category:""
    });
     db.Review.create({
     	{
     	messageBody:"",
     	UserId:"",
     	ChannelId:"",
     	rating:""
     	}
     })
     db.Review.create({
     	{
     	messageBody:"",
     	UserId:"",
     	ChannelId:"",
     	rating:""
     	}
     })
     db.Review.create({
     	{
     	messageBody:"",
     	UserId:"",
     	ChannelId:"",
     	rating:""
     	}
     })
     db.Review.create({
     	{
     	messageBody:"",
     	UserId:"",
     	ChannelId:"",
     	rating:""
     	}
     })
     db.Review.create({
     	{
     	messageBody:"",
     	UserId:"",
     	ChannelId:"",
     	rating:""
     	}
     })
     db.Review.create({
     	{
     	messageBody:"",
     	UserId:"",
     	ChannelId:"",
     	rating:""
     	}
     })
     db.Review.create({
     	{
     	messageBody:"",
     	UserId:"",
     	ChannelId:"",
     	rating:""
     	}
     })
