/*
-- Query: SELECT * FROM review_app_db.Reviews
-- Date: 2017-10-11 22:56
*/
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (1,'PewDiePie is certainly not the greatest creator on the youtube platform, however, his fame and notoriety are certainly not unwarranted',4,'2017-10-12 02:45:17','2017-10-12 02:45:17',2,2);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (2,'The young turks are famous for speaking truth to power and having the most amount of trolls anyone has ever seen',3,'2017-10-12 02:45:17','2017-10-12 02:45:17',4,1);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (3,'Ya boy Ethan the thicc boi, greatest man of all time without a doubt. all Praise lord Ethan.',5,'2017-10-12 02:45:17','2017-10-12 02:45:17',1,4);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (4,'Secular Talk, AKA Kyle Kulinski, AKA the progressinator, a truly principled man with a wonderful comedic capacity',5,'2017-10-12 02:45:17','2017-10-12 02:45:17',3,3);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (5,'Ethan Klein is certaily not underrated and I believe deserves alot more attention than he currently receives. However I really hope he goes back to regularly uploading so we can get some fresh hot memes',4,'2017-10-12 02:45:17','2017-10-12 02:45:17',1,1);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (6,'Pewds, the original nazi fan boy turned social justice target turned shamed swede turned literal ghost. This man changed what it meant to be a human target and contains to be my source of laughter on many occasions.',4,'2017-10-12 02:45:17','2017-10-12 02:45:17',2,1);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (7,'Kyle Kuliski is a liberal cuck who doesn\'t know anything about the world around him. Everyone would be better off just erasing the knowledge of this mans existence from their head',1,'2017-10-12 02:45:17','2017-10-12 02:45:17',3,1);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (8,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',5,'2017-10-12 02:47:57','2017-10-12 02:47:57',1,7);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (9,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',4,'2017-10-12 02:48:05','2017-10-12 02:48:05',2,7);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (10,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',3,'2017-10-12 02:48:12','2017-10-12 02:48:12',3,7);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (11,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',2,'2017-10-12 02:48:20','2017-10-12 02:48:20',4,7);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (12,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',1,'2017-10-12 02:48:24','2017-10-12 02:48:24',5,7);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (13,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',2,'2017-10-12 02:48:28','2017-10-12 02:48:28',4,7);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (14,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',3,'2017-10-12 02:48:32','2017-10-12 02:48:32',3,7);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (15,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',3,'2017-10-12 02:48:48','2017-10-12 02:48:48',6,8);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (16,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',3,'2017-10-12 02:48:54','2017-10-12 02:48:54',7,8);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (17,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',3,'2017-10-12 02:48:56','2017-10-12 02:48:56',8,8);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (18,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',2,'2017-10-12 02:49:02','2017-10-12 02:49:02',8,1);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (19,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',3,'2017-10-12 02:49:06','2017-10-12 02:49:06',8,2);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (20,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',3,'2017-10-12 02:49:15','2017-10-12 02:49:15',9,7);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (21,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',4,'2017-10-12 02:49:20','2017-10-12 02:49:20',9,8);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (22,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',4,'2017-10-12 02:49:26','2017-10-12 02:49:26',10,6);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (23,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',4,'2017-10-12 02:49:33','2017-10-12 02:49:33',10,5);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (24,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',5,'2017-10-12 02:49:36','2017-10-12 02:49:36',11,5);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (25,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',4,'2017-10-12 02:49:44','2017-10-12 02:49:44',12,5);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (26,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',3,'2017-10-12 02:49:50','2017-10-12 02:49:50',13,5);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (27,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',3,'2017-10-12 02:49:56','2017-10-12 02:49:56',14,5);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (28,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',3,'2017-10-12 02:49:58','2017-10-12 02:49:58',15,5);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (29,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',3,'2017-10-12 02:50:01','2017-10-12 02:50:01',16,5);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (30,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',3,'2017-10-12 02:50:07','2017-10-12 02:50:07',17,5);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (31,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',3,'2017-10-12 02:50:09','2017-10-12 02:50:09',18,5);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (32,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',3,'2017-10-12 02:50:12','2017-10-12 02:50:12',19,5);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (33,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',3,'2017-10-12 02:50:17','2017-10-12 02:50:17',20,5);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (34,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',4,'2017-10-12 02:50:26','2017-10-12 02:50:26',21,5);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (35,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',5,'2017-10-12 02:50:30','2017-10-12 02:50:30',21,5);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (36,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',2,'2017-10-12 02:50:39','2017-10-12 02:50:39',22,8);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (37,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',5,'2017-10-12 02:50:45','2017-10-12 02:50:45',22,7);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (38,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',5,'2017-10-12 02:50:50','2017-10-12 02:50:50',23,7);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (39,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',4,'2017-10-12 02:50:55','2017-10-12 02:50:55',23,6);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (40,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',1,'2017-10-12 02:50:59','2017-10-12 02:50:59',24,6);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (41,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',4,'2017-10-12 02:51:06','2017-10-12 02:51:06',24,7);
INSERT INTO `Reviews` (`id`,`messageBody`,`rating`,`createdAt`,`updatedAt`,`ChannelId`,`UserId`) VALUES (42,'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single\n\n',5,'2017-10-12 02:51:10','2017-10-12 02:51:10',24,1);
